/**
 * Curated office favorites around Stampgatan, Gothenburg
 */
const CURATED_RESTAURANTS = [
  {
    id: "jinx-empire",
    name: "Jinx Empire",
    address: "Folkungagatan 20 / Stampgatan",
    lat: 57.7072,
    lng: 11.9860,
    cuisine: "Asian Fusion",
    category: "asian",
    priceSEK: 135,
    lunchHours: "11:00 - 13:30",
    signature: "Pork belly bao buns, bibimbap & Asian street bowls",
    perks: ["Snabb servering", "Kultstatus", "Uteservering"],
    emoji: "🥢",
    website: "https://jinxempire.com",
    isCurated: true
  },
  {
    id: "bruk",
    name: "Bruk",
    address: "Friggagatan 4",
    lat: 57.7102,
    lng: 11.9880,
    cuisine: "Nordic Modern",
    category: "nordic",
    priceSEK: 145,
    lunchHours: "11:30 - 14:00",
    signature: "Säsongsbetonad dagens med salladsbord, surdeg & kaffe",
    perks: ["Salladsbuffé", "Hembakt bröd", "Mysig atmosfär"],
    emoji: "🌿",
    website: "https://brukgbg.se",
    isCurated: true
  },
  {
    id: "birria-seoul",
    name: "Birria Seoul",
    address: "Stampgatan 48",
    lat: 57.7082,
    lng: 11.9875,
    cuisine: "Korean-Mexican",
    category: "streetfood",
    priceSEK: 135,
    lunchHours: "11:00 - 14:30",
    signature: "Birria tacos med dippbuljong & koreanska BBQ-skålar",
    perks: ["Direkt på Stampgatan", "Unika smaker", "Takeaway"],
    emoji: "🌮",
    website: "https://www.instagram.com/birriaseoul/",
    isCurated: true
  },
  {
    id: "ullevi-thaikok",
    name: "Ullevi Thaikök",
    address: "Stampgatan 46",
    lat: 57.7080,
    lng: 11.9870,
    cuisine: "Thai & Wok",
    category: "asian",
    priceSEK: 125,
    lunchHours: "11:00 - 15:00",
    signature: "Klassisk röd curry, pad thai, krispig anka & vårrullar",
    perks: ["Snabbt", "Generösa portioner", "Prisvärt"],
    emoji: "🍲",
    website: "https://ullevithaikok.se",
    isCurated: true
  },
  {
    id: "tomtoms-burritos",
    name: "TomToms Burritos",
    address: "Odinsplatsen 5",
    lat: 57.7092,
    lng: 11.9845,
    cuisine: "Mexican Street Food",
    category: "streetfood",
    priceSEK: 130,
    lunchHours: "11:00 - 15:00",
    signature: "Långbakad carnitas burrito, chipotle bowls & guacamole",
    perks: ["Fräscha råvaror", "Bra vegoalternativ", "Odinsplatsen"],
    emoji: "🌯",
    website: "https://tomtoms.se",
    isCurated: true
  },
  {
    id: "zenviet",
    name: "ZenViet",
    address: "Odinsgatan 5",
    lat: 57.7090,
    lng: 11.9835,
    cuisine: "Vietnamese & Sushi",
    category: "asian",
    priceSEK: 135,
    lunchHours: "11:00 - 14:30",
    signature: "Rykande Phở bo, Bún Chả, fräscha rispappersrullar & sushi",
    perks: ["Hälsosamt", "Färska örter", "Bra soppor"],
    emoji: "🍜",
    website: "https://zenviet.se",
    isCurated: true
  },
  {
    id: "burgersson",
    name: "Burgersson",
    address: "Friggagatan 14B",
    lat: 57.7110,
    lng: 11.9900,
    cuisine: "Gourmet Burgers",
    category: "burgers",
    priceSEK: 145,
    lunchHours: "11:30 - 14:00",
    signature: "Ekologiska premiumburgare, tryffelmajo & handskurna fries",
    perks: ["Svenskt ekokött", "Egenbakat bröd", "Högsta kvalitet"],
    emoji: "🍔",
    website: "https://burgersson.se",
    isCurated: true
  },
  {
    id: "restaurang-pylonen",
    name: "Restaurang Pylonen",
    address: "Ullevi (Paradentrén)",
    lat: 57.7060,
    lng: 11.9885,
    cuisine: "Swedish Husmanskost",
    category: "husman",
    priceSEK: 140,
    lunchHours: "11:00 - 13:30",
    signature: "Klassisk lunchbuffé med köttbullar, dagens fångst & soppa",
    perks: ["Klassisk buffé", "Gott om plats", "Mycket mat"],
    emoji: "🥔",
    website: "https://ullevikonferens.se",
    isCurated: true
  },
  {
    id: "leir-mat-moten",
    name: "Leir Mat & Möten",
    address: "Ullevigatan 17-19",
    lat: 57.7065,
    lng: 11.9845,
    cuisine: "Scandinavian Buffet",
    category: "nordic",
    priceSEK: 145,
    lunchHours: "11:00 - 14:00",
    signature: "Dagens kött, fisk & vego med stort fräscht salladsbord",
    perks: ["Affärslunch", "Ljust & luftigt", "Hälsosam buffé"],
    emoji: "🥗",
    website: "https://leirmatmoten.se",
    isCurated: true
  },
  {
    id: "kalle-glader",
    name: "Kalle Glader",
    address: "Friggagatan 10",
    lat: 57.7106,
    lng: 11.9890,
    cuisine: "Bistro & Pub",
    category: "husman",
    priceSEK: 135,
    lunchHours: "11:30 - 14:30",
    signature: "Krispig schnitzel, raggmunk med stekt fläsk & god husman",
    perks: ["Hemtrevligt", "Rejäla portioner", "Kvarterskrog"],
    emoji: "🍺",
    website: "https://kalleglader.se",
    isCurated: true
  },
  {
    id: "odins-parkgrill",
    name: "Odins Parkgrill",
    address: "Odinsplatsen 11",
    lat: 57.7095,
    lng: 11.9850,
    cuisine: "Street Food & Grill",
    category: "streetfood",
    priceSEK: 110,
    lunchHours: "11:00 - 20:00",
    signature: "Gourmet tunnbrödsrulle, smashburgare & mos med räksallad",
    perks: ["Snabbast", "Klassiskt göteborskt", "Prisvärt"],
    emoji: "🌭",
    website: "https://odinsparkgrill.se",
    isCurated: true
  },
  {
    id: "snack-shack",
    name: "Snack Shack",
    address: "Friggagatan 9",
    lat: 57.7105,
    lng: 11.9885,
    cuisine: "Smashburgers",
    category: "burgers",
    priceSEK: 125,
    lunchHours: "11:30 - 15:00",
    signature: "Oklahoma smashburgare med karamelliserad lök & cheddar",
    perks: ["Krispiga kanter", "Fast casual", "Streetkänsla"],
    emoji: "🍟",
    website: "https://happydaysgbg.se",
    isCurated: true
  },
  {
    id: "glenn-sportsbar",
    name: "Glenn Sportsbar",
    address: "Skånegatan 1 / Ullevi",
    lat: 57.7050,
    lng: 11.9870,
    cuisine: "Pub & Husman",
    category: "husman",
    priceSEK: 135,
    lunchHours: "11:30 - 14:00",
    signature: "Glenns högrevsburgare, fish & chips & dagens kött",
    perks: ["Gôtt tjöt", "Generöst", "Ullevikänsla"],
    emoji: "⚽",
    website: "https://glennsportsbar.se",
    isCurated: true
  },
  {
    id: "sushi-odins",
    name: "Sushi Odins",
    address: "Odinsgatan 13",
    lat: 57.7095,
    lng: 11.9825,
    cuisine: "Sushi & Japanese",
    category: "asian",
    priceSEK: 130,
    lunchHours: "11:00 - 14:30",
    signature: "Nigiri & maki kombo, flamberad lax & yakiniku",
    perks: ["Fräsch fisk", "Snabb take-out", "Misosoppa ingår"],
    emoji: "🍣",
    website: "https://goteborg.com",
    isCurated: true
  },
  {
    id: "trattoria-stampen",
    name: "Trattoria Stampen",
    address: "Stampgatan 28",
    lat: 57.7075,
    lng: 11.9852,
    cuisine: "Italian & Pizza",
    category: "italian",
    priceSEK: 125,
    lunchHours: "11:00 - 14:30",
    signature: "Stenbaksugnspizza, krämig carbonara & pizzasallad",
    perks: ["Precis vid kontoret", "Stenugn", "Klassiker"],
    emoji: "🍕",
    website: "https://thatsup.se",
    isCurated: true
  },
  {
    id: "poppels-city",
    name: "Poppels Citybryggeri",
    address: "Viktor Hasselblad Plats 1",
    lat: 57.7088,
    lng: 11.9772,
    cuisine: "Modern Gastropub & Bryggeri",
    category: "husman",
    priceSEK: 145,
    lunchHours: "11:30 - 14:00",
    signature: "Vällagad dagens lunch & hantverksöl i storslagen miljö",
    perks: ["Fantastisk lokal", "Eget bryggeri", "Hög kvalitet"],
    emoji: "🍺",
    website: "https://poppels.se",
    isCurated: true
  }
];

module.exports = { CURATED_RESTAURANTS };
